name: atacseq_takubo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # --- QC & Trimming ---
  - fastqc=0.12.1
  - trim-galore=0.6.10
  - cutadapt=4.9

  # --- Alignment ---
  - bowtie2=2.5.4
  - samtools=1.21

  # --- Peak Calling ---
  - macs2=2.2.9.1

  # --- BAM processing ---
  - picard=3.2.0
  - bedtools=2.31.1
  - deeptools=3.5.5

  # --- Motif Analysis ---
  - homer=4.11

  # --- R and packages ---
  - r-base=4.3.3
  - bioconductor-genomicranges=1.54.1
  - bioconductor-csaw=1.36.0
  - bioconductor-edger=4.0.16
  - bioconductor-biocparallel=1.36.0
  - r-tidyverse=2.0.0
  - r-data.table=1.15.4
  - r-ggplot2=3.5.1
  - r-pheatmap=1.0.12
  - r-ggrepel=0.9.5
  - r-ggvenn=0.1.10

  # --- Utilities ---
  - pigz=2.8
  - wget=1.21.4
