#!/usr/bin/env bash
# =============================================================================
#  ATAC-seq Pipeline — Project Initializer
#
#  パイプラインコードとプロジェクトデータを分離して管理するための
#  プロジェクトディレクトリ初期化スクリプト。
#
#  使い方:
#    bash init_project.sh /path/to/my_project [genome]
#
#    genome: "hg38" (default) or "mm10"
#
#  生成されるディレクトリ:
#    /path/to/my_project/
#    ├── config.sh          ← プロジェクト固有の設定 (自動生成)
#    ├── samples.tsv        ← サンプルシートテンプレート
#    ├── fastq/             ← FASTQ ファイル配置先
#    └── provenance.yml     ← 実行時自動生成
# =============================================================================
set -euo pipefail

PIPELINE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${PIPELINE_ROOT}/scripts/utils.sh"

# --- 引数チェック ---
if [[ $# -lt 1 ]]; then
  echo "Usage: bash init_project.sh <project_dir> [genome]"
  echo ""
  echo "  project_dir : 新規プロジェクトディレクトリのパス"
  echo "  genome      : hg38 (default) or mm10"
  echo ""
  echo "Example:"
  echo "  bash init_project.sh /data/ATACseq/240101_experiment hg38"
  exit 1
fi

PROJECT_DIR="$(realpath -m "$1")"
GENOME="${2:-hg38}"

# --- バリデーション ---
if [[ -f "${PROJECT_DIR}/config.sh" ]]; then
  echo "ERROR: ${PROJECT_DIR}/config.sh already exists."
  echo "  This project appears to be already initialized."
  echo "  To re-initialize, remove the existing config.sh first."
  exit 1
fi

if [[ "$GENOME" != "hg38" && "$GENOME" != "mm10" ]]; then
  echo "ERROR: Unsupported genome '${GENOME}'. Use 'hg38' or 'mm10'."
  exit 1
fi

# --- ゲノム固有の設定 ---
case "$GENOME" in
  hg38)
    GENOME_SIZE_MACS="hs"
    HOMER_GENOME="hg38"
    STANDARD_CHR_EXPR='$(printf '\''chr%s '\'' {1..22} X)'
    BOWTIE2_INDEX="/home/stemcell/Genome/hg38/hg38"
    BLACKLIST="/home/stemcell/Genome/hg38/hg38_blacklist_v2.bed"
    CHROM_SIZES="/home/stemcell/Genome/hg38/hg38.chrom.sizes"
    ;;
  mm10)
    GENOME_SIZE_MACS="mm"
    HOMER_GENOME="mm10"
    STANDARD_CHR_EXPR='$(printf '\''chr%s '\'' {1..19} X)'
    BOWTIE2_INDEX="/home/stemcell/Genome/mm10/mm10"
    BLACKLIST="/home/stemcell/Genome/mm10/mm10.blacklist.v2_sorted.bed"
    CHROM_SIZES="/home/stemcell/Genome/mm10/mm10.chrom.sizes"
    ;;
esac

# --- ディレクトリ作成 ---
echo "=============================================="
echo " ATAC-seq Pipeline — Project Initializer"
echo " Pipeline: v$(get_pipeline_version) ($(get_git_commit))"
echo "=============================================="
echo ""
echo "Creating project: ${PROJECT_DIR}"
echo "Genome          : ${GENOME}"
echo ""

mkdir -p "${PROJECT_DIR}/fastq"

# --- config.sh 生成 ---
cat > "${PROJECT_DIR}/config.sh" <<CONFIGEOF
#!/usr/bin/env bash
# =============================================================================
#  ATAC-seq Pipeline — Project Configuration
#
#  Generated by init_project.sh
#  Date   : $(date -Iseconds)
#  Pipeline: v$(get_pipeline_version) ($(get_git_commit))
#  Genome : ${GENOME}
# =============================================================================

# --- パイプラインのルートディレクトリ ---
# init_project.sh で初期化した場合、パイプラインコードの場所を指定
PIPELINE_ROOT="${PIPELINE_ROOT}"

# --- プロジェクトのルートディレクトリ ---
DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

# --- サンプルシート ---
SAMPLES_TSV="\${DIR}/samples.tsv"

# =============================================================================
#  GENOME SETTINGS
# =============================================================================
GENOME="${GENOME}"
GENOME_SIZE_MACS="${GENOME_SIZE_MACS}"
HOMER_GENOME="${HOMER_GENOME}"
STANDARD_CHR=( ${STANDARD_CHR_EXPR} )

# =============================================================================
#  FILE PATHS
# =============================================================================
BOWTIE2_INDEX="${BOWTIE2_INDEX}"
BLACKLIST="${BLACKLIST}"
CHROM_SIZES="${CHROM_SIZES}"
PICARD_JAR="\$HOME/picard/picard.jar"

# =============================================================================
#  ENVIRONMENT
# =============================================================================
MACS3_ENV="\$HOME/venvs/venv_macs3/bin/activate"

# =============================================================================
#  PERFORMANCE
# =============================================================================
THREADS=6
MAX_RAM_RECORDS=2500000

# =============================================================================
#  STEP 1 — MAPPING
# =============================================================================
BOWTIE2_MAX_INSERT=700
FILTER_NFR="false"
NFR_MAXFRAG=200

# =============================================================================
#  STEP 2 — PEAK CALLING
# =============================================================================
MACS3_PVALUE="0.01"
MACS3_FORMAT="BAM"
MACS3_NOMODEL="true"
MACS3_EXTSIZE="200"
MACS3_SHIFT="-100"
MACS3_CONTROL_BAMS=()
SUMMIT_HALFWIDTH=125

# =============================================================================
#  STEP 3 — PEAK COUNTS
# =============================================================================
PEAK_LOGCPM_THRESHOLD=""

# =============================================================================
#  STEP 4 — DEEPTOOLS
# =============================================================================
BINSIZE=25

# =============================================================================
#  STEP 5 — DAR
# =============================================================================
DAR_FDR="0.05"
DAR_LFC="0.5"

# =============================================================================
#  STEP 6 — HOMER
# =============================================================================
HOMER_FDR="\${DAR_FDR}"
HOMER_LFC="\${DAR_LFC}"
HOMER_SIZE=250

# =============================================================================
#  OUTPUT DIRECTORIES
# =============================================================================
DIR_TRIMMED="trimmed"
DIR_BAM="BAM"
DIR_PEAKS="Peak_nomodel"
DIR_MERGEDBAM="MergedBAM"
DIR_BW="bw_for_deeptools"
DIR_PLOTS="Plots"
SCRIPT_DIR="\${PIPELINE_ROOT}/scripts"
CONFIGEOF

# --- samples.tsv テンプレート生成 ---
cat > "${PROJECT_DIR}/samples.tsv" <<'SAMPLESEOF'
# ATAC-seq Sample Sheet
# ----------------------
# sample_name : fastq/{sample_name}_{lane}_[12].fq.gz の {sample_name} 部分
# group       : BAM マージ・比較に使うグループ名 (スペース不可)
#
# タブ区切り、# で始まる行はコメント
sample_name	group
SAMPLESEOF

echo "  Created: ${PROJECT_DIR}/config.sh"
echo "  Created: ${PROJECT_DIR}/samples.tsv"
echo "  Created: ${PROJECT_DIR}/fastq/"
echo ""
echo "=============================================="
echo " Project initialized successfully!"
echo "=============================================="
echo ""
echo "Next steps:"
echo "  1. Edit samples.tsv:"
echo "       vim ${PROJECT_DIR}/samples.tsv"
echo ""
echo "  2. Place FASTQ files:"
echo "       cp *.fq.gz ${PROJECT_DIR}/fastq/"
echo ""
echo "  3. (Optional) Edit config.sh to adjust parameters:"
echo "       vim ${PROJECT_DIR}/config.sh"
echo ""
echo "  4. Run the pipeline:"
echo "       bash ${PIPELINE_ROOT}/run_pipeline.sh --config ${PROJECT_DIR}/config.sh"
echo ""
