#!/usr/bin/env bash
# =============================================================================
#  Step 4: Scale Factors & BigWig Generation
#
#  処理内容:
#    1. samples.tsv のグループ定義を基に、グループごとに BAM をマージ
#    2. 04a_scale_factor.R を呼び出し、グループ MergedBAM の
#       ピーク内シグナルからスケールファクターを算出
#    3. deeptools bamCoverage でスケールファクターを適用した CPM 補正 bigWig 生成
#
#  入力:
#    BAM/*.noDup.noMT.filt.sorted.bam
#    Peak_nomodel/Peaks_250bp_th0.bed
#  出力:
#    MergedBAM/{group}.noBL.filtered.sorted.bam
#    Peak_nomodel/scale_factors.tsv
#    bw_for_deeptools/{group}.bw
# =============================================================================
set -euo pipefail
source "$(dirname "$0")/../config.sh"

# --- Substep support ---
FROM_SUB="${PIPELINE_FROM_SUBSTEP:-}"
FORCE="${PIPELINE_FORCE:-false}"
should_run_sub() { local sub="$1"; [[ -z "${FROM_SUB}" || ! "${sub}" < "${FROM_SUB}" ]]; }
if [[ -n "${FROM_SUB}" ]]; then
  echo "  Substep start: ${FROM_SUB}"
fi

MERGE_DIR="${DIR}/${DIR_MERGEDBAM}"
BAM_DIR="${DIR}/${DIR_BAM}"
BW_DIR="${DIR}/${DIR_BW}"
PEAK_DIR="${DIR}/${DIR_PEAKS}"
SCRIPT_DIR_SELF="$(dirname "$0")"

mkdir -p "${MERGE_DIR}" "${BW_DIR}"

# --- グループ一覧取得 ---
get_groups() {
  grep -v "^#" "${SAMPLES_TSV}" | grep -v "^$" | grep -v "^sample_name" | \
    awk -F'\t' '{print $2}' | sort -u
}

get_samples_in_group() {
  local grp="$1"
  grep -v "^#" "${SAMPLES_TSV}" | grep -v "^$" | grep -v "^sample_name" | \
    awk -F'\t' -v g="${grp}" '$2 == g {print $1}'
}

# =============================================================================
#  [a] グループごとに BAM マージ → blacklist 除去 → sort → index
# =============================================================================
if should_run_sub a; then
echo "--- [a] Merging BAM files per group ---"
while IFS= read -r group; do
  OUT_BASE="${MERGE_DIR}/${group}.noBL.filtered.sorted"
  MERGED_BAM="${OUT_BASE}.bam"

  if [[ -f "${MERGED_BAM}" && -f "${MERGED_BAM}.bai" ]]; then
    echo "  [${group}] Merged BAM already exists. Skipping."
    continue
  fi

  # グループ内の sample BAM 収集
  bam_list=()
  while IFS= read -r sample; do
    bam="${BAM_DIR}/${sample}.noDup.noMT.filt.sorted.bam"
    if [[ -f "$bam" ]]; then
      bam_list+=("$bam")
    else
      echo "  WARNING: BAM not found for sample '${sample}': ${bam}"
    fi
  done < <(get_samples_in_group "${group}")

  if [[ ${#bam_list[@]} -eq 0 ]]; then
    echo "  ERROR: No BAM files for group '${group}'. Skipping."
    continue
  fi

  echo "  [${group}] Merging ${#bam_list[@]} BAM(s)..."

  TEMP_MERGED="${MERGE_DIR}/${group}.tmp_merged.bam"

  if [[ ${#bam_list[@]} -eq 1 ]]; then
    # 単一サンプルのグループはシンボリックコピー
    cp "${bam_list[0]}" "${TEMP_MERGED}"
  else
    samtools merge -f -@ "${THREADS}" "${TEMP_MERGED}" "${bam_list[@]}"
  fi

  # Blacklist 除去
  echo "  [${group}] Removing blacklist regions..."
  TEMP_NOBL="${MERGE_DIR}/${group}.tmp_noBL.bam"
  bedtools intersect -v \
    -a "${TEMP_MERGED}" \
    -b "${BLACKLIST}" \
    > "${TEMP_NOBL}"
  rm -f "${TEMP_MERGED}"

  # Sort & index
  samtools sort -@ "${THREADS}" -o "${MERGED_BAM}" "${TEMP_NOBL}"
  samtools index -@ "${THREADS}" "${MERGED_BAM}"
  rm -f "${TEMP_NOBL}"

  echo "  [${group}] Done: ${MERGED_BAM}"
done < <(get_groups)
fi  # end substep a

# =============================================================================
#  [b] スケールファクター算出 (R)
# =============================================================================
SCALE_TSV="${PEAK_DIR}/scale_factors.tsv"
if should_run_sub b; then
  echo ""
  echo "--- [b] Computing scale factors ---"
  Rscript "${SCRIPT_DIR_SELF}/04a_scale_factor.R"
  if [[ ! -f "${SCALE_TSV}" ]]; then
    echo "ERROR: scale_factors.tsv not generated by 04a_scale_factor.R"
    exit 1
  fi
  echo "Scale factors:"
  cat "${SCALE_TSV}"
else
  if [[ ! -f "${SCALE_TSV}" ]]; then
    echo "ERROR: scale_factors.tsv not found. Run substep b first:  ./run_pipeline.sh --from 4b"
    exit 1
  fi
  echo "--- [b] Skipped (using existing scale_factors.tsv) ---"
fi  # end substep b

# =============================================================================
#  [c] bamCoverage (CPM 補正 + スケールファクター適用)
# =============================================================================
if should_run_sub c; then
  echo ""
  echo "--- [c] Generating bigWig files ---"
  while IFS=$'\t' read -r group scale_factor; do
    [[ "$group" == "group" ]] && continue  # ヘッダースキップ
    BAM="${MERGE_DIR}/${group}.noBL.filtered.sorted.bam"
    BW_OUT="${BW_DIR}/${group}.bw"

    if [[ ! -f "$BAM" ]]; then
      echo "  WARNING: merged BAM not found for group '${group}'. Skipping bigWig."
      continue
    fi

    if [[ "${FORCE}" != "true" && -f "${BW_OUT}" ]]; then
      echo "  [${group}] bigWig already exists, skipping (use --force to redo)"
      continue
    fi

    echo "  [${group}] scale_factor=${scale_factor}"
    bamCoverage \
      --bam "${BAM}" \
      --outFileName "${BW_OUT}" \
      --outFileFormat bigwig \
      --scaleFactor "${scale_factor}" \
      --normalizeUsing CPM \
      --blackListFileName "${BLACKLIST}" \
      --ignoreDuplicates \
      --centerReads \
      --binSize "${BINSIZE}" \
      --numberOfProcessors "${THREADS}" \
      2>&1 | grep -v "^bamFilesList\|^genomeSize\|^Effective"
    echo "  → ${BW_OUT}"
  done < "${SCALE_TSV}"
fi  # end substep c

echo ""
echo "Step 4 complete."
echo "  MergedBAM : ${MERGE_DIR}"
echo "  BigWig    : ${BW_DIR}"
